theme: jekyll-theme-cayman
title: Sebastian Bayer
description: Data Scientist at the Robert Bosch Center for Artificial Intelligence with strong interests in econometrics, predictive modelling, optimization and programming.
